### ISSUE TITLE
Camera module broken!

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/TAPP#1]
Traceback (most recent call last):
  File "./tapp.py", line 74, in <module>
    main()
  File "./tapp.py", line 68, in main
    camera.snap(pose)
  File "/home/ntlhui/workspace/TAPP/TAPP/Camera.py", line 52, in snap
    ply_utils.ply_face2vertices(face[0], vertices)
AttributeError: 'module' object has no attribute 'ply_face2vertices'

**Comment by ntlhui** [comment]
Fixed
