### ISSUE TITLE
ply_utils.py:face2vertices seems to be broken

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/TAPP#2]
tapp.py data/tif/canyon_dem_clipped.tif data/canyon_dem_clipped_search_area.txt data/sl1_params.txt data/poses.csv 
Got args
Trimming tiff
Tiff -> Mesh
Loading camera params
Loading camera poses
Processing poses
305337251.000000, 361874654.000000, 15.000000, 0.000000, 0.000000, 0.000000
Traceback (most recent call last):
  File "/usr/local/bin/tapp.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ntlhui/workspace/TAPP/tapp.py", line 82, in <module>
    main()
  File "/home/ntlhui/workspace/TAPP/tapp.py", line 76, in main
    camera.snap(pose)
  File "/home/ntlhui/workspace/TAPP/TAPP/Camera.py", line 51, in snap
    ply_utils.face2vertices(face[0], vertices)
  File "/home/ntlhui/workspace/TAPP/utils/ply_utils.py", line 10, in face2vertices
    vert3 = np.asarray([vert for vert in vertices[face[2]]])
IndexError: index 153543 is out of bounds for axis 0 with size 153543

**Comment by matte1** [comment]
Fixed an issue in tif2mesh that was causing this problem. Try to break it again with some more tif or different trimmings for tifs
